-- Generated by `pikku db generate` from pikkuBetterAuth (Better Auth).
-- Re-run the command after changing that source.

-- REVIEWED: given a DEFAULT '' rather than left bare. SQLite rejects
-- `ADD COLUMN ... NOT NULL` with no default outright — it is a DDL-time error, not
-- a data-time one, so it fails even on the empty table this project always starts
-- from. Better Auth writes `issuer` on every row it creates; the default only ever
-- applies to rows that predate the column, and this project has none.
ALTER TABLE account ADD COLUMN issuer TEXT NOT NULL DEFAULT '';
