-- Generated by `pikku db generate` from @pikku/kysely's runtime services.
-- Re-run the command after changing that source.

create table "audit" ("audit_id" text primary key, "occurred_at" text not null, "type" text not null, "source" text default 'auto' not null, "outcome" text, "function_id" text, "wire_type" text, "trace_id" text, "transaction_id" text, "query_id" text, "user_id" text, "org_id" text, "pikku_user_id" text, "tables" text, "changed_cols" text, "event" text, "old" text, "data" text);

create index "idx_audit_occurred_at" on "audit" ("occurred_at");

create index "idx_audit_user_id" on "audit" ("user_id");

create index "idx_audit_type" on "audit" ("type");
