-- Intentionally empty.
--
-- Everything that used to live here — the running order, the pointer, and the
-- fixture board — is in db/sqlite/0008-meetup-schedule.sql, so that a deployed
-- stage comes up with the same data `pikku db reset` produces. That was done on
-- the day of the talk, to get a demo standing up; the fixtures do not belong in
-- a migration, and the split back into real content here and dev-only fixtures
-- there is the first thing to undo afterwards.
